import recommended from "@timmo001/oxlint-rules/configs/recommended";
import { defineConfig } from "oxlint";

export default defineConfig({
  extends: [recommended],
  plugins: ["typescript", "unicorn", "oxc"],
  jsPlugins: ["eslint-plugin-lit"],
  categories: {
    correctness: "error"
  },
  options: {
    typeAware: true,
    typeCheck: true,
    maxWarnings: 0
  },
  // These JavaScript files are generated by scripts/build.mjs.
  ignorePatterns: [
    "node_modules/**",
    "extension/background.js",
    "extension/popup.js",
    "extension/sites/*/content.js"
  ],
  rules: {
    "typescript/no-explicit-any": "error",
    "typescript/no-floating-promises": "error",
    "typescript/no-misused-promises": "error",
    "typescript/no-unnecessary-type-assertion": "error",
    "typescript/no-unsafe-argument": "error",
    "typescript/no-unsafe-assignment": "error",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-member-access": "error",
    "typescript/no-unsafe-return": "error"
  },
  overrides: [
    {
      files: ["src/**/*.ts"],
      env: { browser: true, webextensions: true },
      // Lit's recommended rules catch malformed bindings and update loops.
      rules: {
        "lit/attribute-value-entities": "error",
        "lit/binding-positions": "error",
        "lit/no-duplicate-template-bindings": "error",
        "lit/no-invalid-html": "error",
        "lit/no-legacy-template-syntax": "error",
        "lit/no-property-change-update": "error",
        "lit/lifecycle-super": "error",
        "lit/no-classfield-shadowing": "error"
      }
    },
    {
      files: ["scripts/**/*.mjs", "tests/**/*.mjs", "*.config.ts"],
      env: { node: true }
    }
  ]
});
