---
name: Build

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    uses: timmo001/workflows/.github/workflows/build-pnpm.yml@7ca73488f2c4d16f40e6fbc8afad83ffab7b96fd # master
    with:
      build-command: pnpm check
      artifact-name: site-defluffer-extension
      artifact-path: extension
