---
name: Build

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    uses: timmo001/workflows/.github/workflows/build-pnpm.yml@bab9f4819faa46f068e90d85657cb9be7ee85af4 # master
    with:
      build-command: pnpm check
      artifact-name: site-defluffer-extension
      artifact-path: extension
