---
name: Build

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    uses: timmo001/workflows/.github/workflows/build-pnpm.yml@db1c7b0288facbdf5afe34db9135d960992049ba # master
    with:
      build-command: pnpm check
      additional-build-commands: git diff --exit-code -- extension
      artifact-name: site-defluffer-extension
      artifact-path: extension
