---
name: Lint

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  actionlint:
    uses: timmo001/workflows/.github/workflows/lint-actionlint.yml@e953abab0d2a7992524b94194d27231c75b2e130 # master

  markdownlint:
    uses: timmo001/workflows/.github/workflows/lint-markdownlint.yml@e953abab0d2a7992524b94194d27231c75b2e130 # master

  yamllint:
    uses: timmo001/workflows/.github/workflows/lint-yamllint.yml@e953abab0d2a7992524b94194d27231c75b2e130 # master

  jsonlint:
    uses: timmo001/workflows/.github/workflows/lint-jsonlint.yml@e953abab0d2a7992524b94194d27231c75b2e130 # master

  shellcheck:
    uses: timmo001/workflows/.github/workflows/lint-shellcheck.yml@e953abab0d2a7992524b94194d27231c75b2e130 # master
    with:
      scandir: scripts
      severity: warning
