---
name: Lint

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  actionlint:
    uses: timmo001/workflows/.github/workflows/lint-actionlint.yml@b1733d0a2934e73b847b22acec65e75a0f113aa6 # master

  markdownlint:
    uses: timmo001/workflows/.github/workflows/lint-markdownlint.yml@b1733d0a2934e73b847b22acec65e75a0f113aa6 # master

  yamllint:
    uses: timmo001/workflows/.github/workflows/lint-yamllint.yml@b1733d0a2934e73b847b22acec65e75a0f113aa6 # master

  jsonlint:
    uses: timmo001/workflows/.github/workflows/lint-jsonlint.yml@b1733d0a2934e73b847b22acec65e75a0f113aa6 # master

  shellcheck:
    uses: timmo001/workflows/.github/workflows/lint-shellcheck.yml@b1733d0a2934e73b847b22acec65e75a0f113aa6 # master
    with:
      scandir: scripts
      severity: warning
