---
name: Lint

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  actionlint:
    uses: timmo001/workflows/.github/workflows/lint-actionlint.yml@0bd0ea1f97a11bcda79f22b9ebca8007b1e76b40 # master

  markdownlint:
    uses: timmo001/workflows/.github/workflows/lint-markdownlint.yml@0bd0ea1f97a11bcda79f22b9ebca8007b1e76b40 # master

  yamllint:
    uses: timmo001/workflows/.github/workflows/lint-yamllint.yml@0bd0ea1f97a11bcda79f22b9ebca8007b1e76b40 # master

  jsonlint:
    uses: timmo001/workflows/.github/workflows/lint-jsonlint.yml@0bd0ea1f97a11bcda79f22b9ebca8007b1e76b40 # master

  shellcheck:
    uses: timmo001/workflows/.github/workflows/lint-shellcheck.yml@0bd0ea1f97a11bcda79f22b9ebca8007b1e76b40 # master
    with:
      scandir: scripts
      severity: warning
