---
name: Renovate automerge

# yamllint disable-line rule:truthy
on:
  pull_request_target: {}

jobs:
  automerge:
    uses: timmo001/workflows/.github/workflows/renovate-automerge.yml@b1733d0a2934e73b847b22acec65e75a0f113aa6 # master
    permissions:
      pull-requests: write
      contents: write
