---
name: Renovate automerge

# yamllint disable-line rule:truthy
on:
  pull_request_target: {}

jobs:
  automerge:
    uses: timmo001/workflows/.github/workflows/renovate-automerge.yml@6391eb6416fc711a5d6c1c96b6b4a4b8c16af5af # master
    permissions:
      pull-requests: write
      contents: write
